version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: tadeustore-rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=master
      - RABBITMQ_DEFAULT_PASS=master
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis
    container_name: tadeustore-redis
    command: redis-server
    ports:
      - "6379:6379"

  sql-server:
    image: mcr.microsoft.com/mssql/rhel/server:2019-CU1-rhel-8
    container_name: tadeustore-sql-container
    working_dir: /usr/src/app
    volumes:
      - /var/opt/mssql
      - ./:/usr/src/app
    command: sh -c ' chmod +x ./Sql/entrypoint.sh; ./Sql/entrypoint.sh & /opt/mssql/bin/sqlservr;'
    environment:
      SA_PASSWORD: "Password!@#"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433

  sonarqube:
    image: sonarqube:lts-community
    container_name: tadeustore-sonarqube
    command: "-Dsonar.search.javaAdditionalOpts=-Dnode.store.allow_mmap=false"
    ports:
      - 9000:9000
    volumes:
      - sonarqube-conf:/opt/sonarqube/conf
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions
      - sonarqube-bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    environment:
      - SONARQUBE_JDBC_URL=jdbc:sqlserver://sql-server;databaseName=SONAR
      - SONARQUBE_JDBC_USERNAME=sa
      - SONARQUBE_JDBC_PASSWORD=Password!@#
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    depends_on:
      - sql-server

  web-api:
    image: tadeustore-api:latest
    container_name: tadeustore-api-container
    build:
      context: ../TadeuStore/
      dockerfile: TadeuStore.API/Dockerfile
    ports:
      - 5001:5001
      - 5003:5003
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5001;http://*:5003
    depends_on:
      - rabbitmq

  consumer:
    image: tadeustore-consumer:latest
    container_name: tadeustore-consumer-container
    build:
      context: ../TadeuStore/
      dockerfile: TadeuStore.Consumer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - rabbitmq
      - web-api

volumes:
  sonarqube-conf:
  sonarqube-data:
  sonarqube-extensions:
  sonarqube-bundled-plugins:
