IF NOT EXISTS (SELECT name FROM master.sys.databases WHERE name = N'SONAR')
BEGIN
	CREATE DATABASE SONAR COLLATE SQL_Latin1_General_CP1_CS_AS;

	ALTER DATABASE SONAR SET READ_COMMITTED_SNAPSHOT ON WITH ROLLBACK IMMEDIATE;
END;